### ISSUE TITLE
Javascript is not running in login page

### ISSUE THREAD

**Issue by ByungkwonJeon** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#27] opened 2019-05-22 19:18 UTC
I enabled on the javascript enforcing page layout. And when I test with postman and 'run user flow', I can see javascript is running on login page. But with MSAL library the javascript is not running on login page. Can you please provide any advice to run the script?

**Comment by jennyf19** [comment] 2019-09-12 01:48
@pkanher617 thoughts on this?

**Comment by sameerag** [comment] 2020-01-23 22:37
Can you please try the latest sample and [msal js](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/v1.2.1) and have us know if this is still an issue? Please raise a new issue if this exists with clear steps to repro and sample code. 

Closing this now.

**Closed as completed by sameerag** 2020-01-23 22:37 UTC

**Comment by BrioLichen** [comment] 2020-01-23 23:03
@sameerag why should i update the sample to the latest version of the msal js? shouldn't the maintainers of this sample be doing that? and why close this issue?

**Comment by sameerag** [comment] 2020-01-23 23:05
Apologies for any confusion, I have updated the sample (#47) with the latest code. Can you try that once merged? 

Since the issue is raised before some time, wanted to ensure if this is still an open issue for you. Pls comment here once you are able to test and I will reopen/track with a new issue if the original issue persists.
