### ISSUE TITLE
Sample might not work with MSA or Twitter

### ISSUE THREAD

**Issue by SaeedAkhter-MSFT** [Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp#2] opened 2017-05-10 20:25 UTC
This sample works with most social providers but there is a possible issue with MSA and Twitter that we are investigating.  We will update this sample if necessary.

**Comment by jmprieur** [comment] 2017-05-11 15:48
Closing as duplicate as the issue is mentioned and explained in the README.md

**Closed as completed by jmprieur** 2017-05-11 15:48 UTC
Labels: duplicate
